name: Actions workflow

on: [push]

jobs:
  run-github-actions:
    runs-on:  ubuntu-latest
    steps:  
      - name: List all Files
        run:  |
          pwd
          ls -lart
      - name: Checkout the Repository
        uses: actions/checkout@v1
      - name: List all Files after checkout
        run:  |
          pwd
          ls -lart
      - name: Simple JS Actions
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: Omansh
      - name: Log Greeting Time
        run:  echo "${{ steps.greet.outputs.time }}"