name: Decrypt Env Variable

on:
  push:
    branches:
      - develop

jobs:
  decrypt:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Decrypt the file
        run:  gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" --output $HOME/secret.json secrets.json.gpg
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
      - name: Print out file content
        run:  cat $HOME/secret.json