name: Shell Commands

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  pull_request_target:
    branches:
      - master

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script
        run:  |
          node -v
          npm -v
      - name: Fetch ENV Variable
        run:  |
          echo GITHUB_REF: $GITHUB_REF
          echo GITHUB_REPOSITORY: $GITHUB_REPOSITORY
          echo GITHUB_BASE_REF: $GITHUB_BASE_REF
          echo GITHUB_HEAD_REF: $GITHUB_HEAD_REF
