name: Strategy Demonstration

on:
  push:
    branches:
      - develop

jobs:
  node-version:
    runs-on:  ubuntu-latest
    steps:
      - name: Check node version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: 6
      - name: Check node version again
        run:  node -v