name: Strategy Demonstration

on:
  push:
    branches:
      - develop

jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node_version: [6,8,10]
      # fail-fast:  true
      # max-parallel: 2
    runs-on:  ${{ matrix.os }}
    steps:
      - name: Check node version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Check node version again
        run:  node -v