name: Shell Commands

on: 
  push:
    branches:
      - master

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: echo the secret value
        env:
         SSH_KEY: ${{ secrets.SECRETKEY }}
         SSH_KEY_TEST: ${{ secrets.test }}
        run: |
          echo ${{ secrets.SECRETKEY }}
          echo $SSH_KEY
